"""Branded PDF documents for invoices and quotes (fpdf2, pure python)."""
from decimal import Decimal
from fpdf import FPDF
from app.config import get_settings

settings = get_settings()

NAVY = (1, 24, 78)
GRAY = (110, 118, 130)
LIGHT = (243, 244, 247)


def _txt(value) -> str:
    """Core fonts are latin-1 only; degrade unknown glyphs instead of crashing."""
    return str(value if value is not None else "").encode("latin-1", "replace").decode("latin-1")


class _BrandedPDF(FPDF):
    def __init__(self, doc_title: str):
        super().__init__()
        self.doc_title = doc_title
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 26, "F")
        self.set_font("helvetica", "B", 16)
        self.set_text_color(255, 255, 255)
        self.set_xy(12, 8)
        self.cell(100, 10, _txt(settings.app_name.replace(" API", "")))
        self.set_font("helvetica", "B", 13)
        self.set_xy(120, 8)
        self.cell(78, 10, _txt(self.doc_title), align="R")
        self.set_y(34)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-16)
        self.set_font("helvetica", "", 8)
        self.set_text_color(*GRAY)
        footer = settings.company_details or f"Generated by {settings.app_name.replace(' API', '')}"
        self.cell(0, 8, _txt(footer.replace("\n", "  ·  ")), align="C")

    def meta_row(self, label: str, value: str):
        self.set_font("helvetica", "", 10)
        self.set_text_color(*GRAY)
        self.cell(40, 6, _txt(label))
        self.set_text_color(0, 0, 0)
        self.set_font("helvetica", "B", 10)
        self.cell(0, 6, _txt(value), new_x="LMARGIN", new_y="NEXT")

    def items_table(self, headers: list[str], widths: list[int], rows: list[list[str]]):
        self.ln(4)
        self.set_font("helvetica", "B", 9)
        self.set_fill_color(*NAVY)
        self.set_text_color(255, 255, 255)
        for h, w in zip(headers, widths):
            self.cell(w, 8, _txt(h), fill=True, align="R" if h != headers[0] else "L")
        self.ln()
        self.set_text_color(0, 0, 0)
        self.set_font("helvetica", "", 9)
        fill = False
        for row in rows:
            if fill:
                self.set_fill_color(*LIGHT)
            for i, (cell, w) in enumerate(zip(row, widths)):
                self.cell(w, 7, _txt(cell), fill=fill, align="R" if i != 0 else "L")
            self.ln()
            fill = not fill

    def total_line(self, label: str, value: str, bold: bool = True):
        self.set_font("helvetica", "B" if bold else "", 11 if bold else 10)
        self.cell(140, 8, _txt(label), align="R")
        self.cell(46, 8, _txt(value), align="R", new_x="LMARGIN", new_y="NEXT")


def build_invoice_pdf(invoice, client, project, time_entries, quote, paid_total: Decimal) -> bytes:
    pdf = _BrandedPDF("INVOICE")
    pdf.add_page()

    # Two-column header: BILLED TO (left) | invoice meta (right)
    top = pdf.get_y() + 2
    pdf.set_xy(12, top)
    pdf.set_font("helvetica", "B", 8)
    pdf.set_text_color(*GRAY)
    pdf.cell(90, 5, "BILLED TO")
    pdf.set_xy(12, top + 6)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(90, 6, _txt(client.name if client else "-"))
    y = top + 13
    if client and getattr(client, "contact_email", None):
        pdf.set_xy(12, y)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(90, 5, _txt(client.contact_email))
        y += 6
    if project:
        pdf.set_xy(12, y)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(90, 5, _txt(f"Project: {project.name}"))
        y += 6

    right_rows = [("Invoice #", invoice.number)]
    if invoice.issued_at:
        right_rows.append(("Issued", str(invoice.issued_at)))
    if invoice.due_date:
        right_rows.append(("Due", str(invoice.due_date)))
    right_rows.append(("Status", invoice.status.upper()))
    ry = top
    for label, value in right_rows:
        pdf.set_xy(120, ry)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(38, 5, _txt(label), align="R")
        pdf.set_font("helvetica", "B", 9)
        if label == "Status" and invoice.status == "paid":
            pdf.set_text_color(22, 130, 60)
        elif label == "Status" and invoice.status == "overdue":
            pdf.set_text_color(200, 40, 40)
        else:
            pdf.set_text_color(0, 0, 0)
        pdf.cell(40, 5, _txt(value), align="R")
        ry += 6
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(max(y, ry) + 2)

    if getattr(invoice, "items", None):
        rows = [
            [i.description[:70], f"{i.quantity}", f"{i.unit_price}",
             f"{(i.quantity * i.unit_price).quantize(Decimal('0.01'))}"]
            for i in invoice.items
        ]
        pdf.items_table(["Item", "Qty", "Unit price", "Amount"], [96, 25, 32, 33], rows)
    elif time_entries:
        rows = [
            [f"{e.work_date}  {(e.description or 'Work')[:60]}", f"{e.hours}",
             f"{e.hourly_rate if e.hourly_rate is not None else (project.hourly_rate if project else '')}"]
            for e in time_entries
        ]
        pdf.items_table(["Time entry", "Hours", "Rate"], [126, 30, 30], rows)
    elif quote and quote.items:
        rows = [
            [i.description[:70], f"{i.quantity}", f"{i.unit_price}",
             f"{(i.quantity * i.unit_price).quantize(Decimal('0.01'))}"]
            for i in quote.items
        ]
        pdf.items_table(["Item", "Qty", "Unit price", "Amount"], [96, 25, 32, 33], rows)
    else:
        pdf.items_table(["Description", "Amount"], [140, 46], [["Professional services", f"{invoice.amount}"]])

    pdf.ln(2)
    pdf.total_line(f"Total ({invoice.currency})", f"{invoice.amount}")
    if invoice.fx_currency and invoice.fx_rate:
        converted = (invoice.amount * invoice.fx_rate).quantize(Decimal("0.01"))
        rate_str = f"{Decimal(invoice.fx_rate).normalize():f}"
        pdf.total_line(f"Equivalent ({invoice.fx_currency} @ {rate_str})", f"{converted:,}", bold=False)
    if paid_total and paid_total > 0:
        pdf.total_line("Paid", f"{paid_total}", bold=False)
        balance = (invoice.amount - paid_total).quantize(Decimal("0.01"))
        pdf.total_line("Balance due", f"{balance}")
        if balance <= 0:
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(22, 130, 60)
            pdf.cell(0, 10, "PAID - THANK YOU", align="R", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)

    # Payment details box (how to pay)
    if invoice.bank_name or invoice.account_number or invoice.account_title:
        pdf.ln(6)
        box_top = pdf.get_y()
        pdf.set_fill_color(*LIGHT)
        rows = [r for r in [
            ("Bank", invoice.bank_name),
            ("Account title", invoice.account_title),
            ("Account number", invoice.account_number),
        ] if r[1]]
        pdf.rect(12, box_top, 110, 8 + 6 * len(rows), "F")
        pdf.set_xy(16, box_top + 2)
        pdf.set_font("helvetica", "B", 8)
        pdf.set_text_color(*NAVY)
        pdf.cell(100, 5, "PAYMENT DETAILS")
        yy = box_top + 8
        for label, value in rows:
            pdf.set_xy(16, yy)
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(*GRAY)
            pdf.cell(32, 5, _txt(label))
            pdf.set_font("helvetica", "B", 9)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(70, 5, _txt(value))
            yy += 6
        pdf.set_y(yy + 2)
    return bytes(pdf.output())


def build_quote_pdf(quote) -> bytes:
    pdf = _BrandedPDF("PROPOSAL")
    pdf.add_page()
    pdf.meta_row("Proposal", quote.number)
    pdf.meta_row("Prepared for", quote.client.name if quote.client else (quote.lead.company_name if quote.lead else "-"))
    pdf.meta_row("Title", quote.title)
    if quote.valid_until:
        pdf.meta_row("Valid until", str(quote.valid_until))

    rows = [
        [i.description[:70], f"{i.quantity}", f"{i.unit_price}",
         f"{(i.quantity * i.unit_price).quantize(Decimal('0.01'))}"]
        for i in quote.items
    ]
    pdf.items_table(["Item", "Qty", "Unit price", "Amount"], [96, 25, 32, 33], rows)
    pdf.ln(2)
    pdf.total_line(f"Total ({quote.currency})", f"{quote.total}")
    if quote.terms:
        pdf.ln(6)
        pdf.set_font("helvetica", "B", 9)
        pdf.cell(0, 6, "Terms", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.multi_cell(0, 5, _txt(quote.terms))
    return bytes(pdf.output())
