"""Branded PDF documents for invoices and quotes (fpdf2, pure python)."""
from decimal import Decimal
from pathlib import Path
from fpdf import FPDF
from app.config import get_settings

settings = get_settings()

# White transparent brand mark, shipped with the frontend; optional at runtime
_LOGO_PATH = Path(__file__).resolve().parents[3] / "frontend" / "public" / "brand-mark.png"

NAVY = (1, 24, 78)
GRAY = (110, 118, 130)
LIGHT = (243, 244, 247)


_PUNCT = str.maketrans({
    "\u2014": "-", "\u2013": "-", "\u2012": "-", "\u2010": "-", "\u2011": "-",
    "\u2018": "'", "\u2019": "'", "\u201a": "'", "\u201c": '"', "\u201d": '"', "\u201e": '"',
    "\u2026": "...", "\u2022": "-", "\u00a0": " ", "\u2009": " ", "\u202f": " ", "\u2192": "->", "\u2713": "v", "\u2714": "v",
})


def _txt(value) -> str:
    """Core fonts are latin-1 only: map common Unicode punctuation to ASCII, degrade the rest."""
    return str(value if value is not None else "").translate(_PUNCT).encode("latin-1", "replace").decode("latin-1")


class _BrandedPDF(FPDF):
    def __init__(self, doc_title: str):
        super().__init__()
        self.doc_title = doc_title
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 26, "F")
        text_x = 12
        if _LOGO_PATH.is_file():
            try:
                self.image(str(_LOGO_PATH), x=10, y=3, h=20)
                text_x = 30
            except Exception:
                pass
        self.set_font("helvetica", "B", 16)
        self.set_text_color(255, 255, 255)
        self.set_xy(text_x, 8)
        self.cell(100, 10, _txt(settings.app_name.replace(" API", "")))
        self.set_font("helvetica", "B", 13)
        self.set_xy(120, 8)
        self.cell(78, 10, _txt(self.doc_title), align="R")
        self.set_y(34)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-16)
        self.set_font("helvetica", "", 8)
        self.set_text_color(*GRAY)
        footer = settings.company_details or f"Generated by {settings.app_name.replace(' API', '')}"
        self.cell(0, 8, _txt(footer.replace("\n", "  ·  ")), align="C")

    def meta_row(self, label: str, value: str):
        self.set_font("helvetica", "", 10)
        self.set_text_color(*GRAY)
        self.cell(40, 6, _txt(label))
        self.set_text_color(0, 0, 0)
        self.set_font("helvetica", "B", 10)
        self.cell(0, 6, _txt(value), new_x="LMARGIN", new_y="NEXT")

    def items_table(self, headers: list[str], widths: list[int], rows: list[list[str]]):
        self.ln(4)
        self.set_font("helvetica", "B", 9)
        self.set_fill_color(*NAVY)
        self.set_text_color(255, 255, 255)
        for h, w in zip(headers, widths):
            self.cell(w, 8, _txt(h), fill=True, align="R" if h != headers[0] else "L")
        self.ln()
        self.set_text_color(0, 0, 0)
        self.set_font("helvetica", "", 9)
        fill = False
        for row in rows:
            if fill:
                self.set_fill_color(*LIGHT)
            for i, (cell, w) in enumerate(zip(row, widths)):
                self.cell(w, 7, _txt(cell), fill=fill, align="R" if i != 0 else "L")
            self.ln()
            fill = not fill

    def total_line(self, label: str, value: str, bold: bool = True):
        self.set_font("helvetica", "B" if bold else "", 11 if bold else 10)
        self.cell(140, 8, _txt(label), align="R")
        self.cell(46, 8, _txt(value), align="R", new_x="LMARGIN", new_y="NEXT")


def build_invoice_pdf(invoice, client, project, time_entries, quote, paid_total: Decimal) -> bytes:
    pdf = _BrandedPDF("INVOICE")
    pdf.add_page()

    # Two-column header: BILLED TO (left) | invoice meta (right)
    top = pdf.get_y() + 2
    pdf.set_xy(12, top)
    pdf.set_font("helvetica", "B", 8)
    pdf.set_text_color(*GRAY)
    pdf.cell(90, 5, "BILLED TO")
    pdf.set_xy(12, top + 6)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(90, 6, _txt(client.name if client else "-"))
    y = top + 13
    if client and getattr(client, "contact_email", None):
        pdf.set_xy(12, y)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(90, 5, _txt(client.contact_email))
        y += 6
    if project:
        pdf.set_xy(12, y)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(90, 5, _txt(f"Project: {project.name}"))
        y += 6

    right_rows = [("Invoice #", invoice.number)]
    if invoice.issued_at:
        right_rows.append(("Issued", str(invoice.issued_at)))
    if invoice.due_date:
        right_rows.append(("Due", str(invoice.due_date)))
    right_rows.append(("Status", invoice.status.upper()))
    ry = top
    for label, value in right_rows:
        pdf.set_xy(120, ry)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(38, 5, _txt(label), align="R")
        pdf.set_font("helvetica", "B", 9)
        if label == "Status" and invoice.status == "paid":
            pdf.set_text_color(22, 130, 60)
        elif label == "Status" and invoice.status == "overdue":
            pdf.set_text_color(200, 40, 40)
        else:
            pdf.set_text_color(0, 0, 0)
        pdf.cell(40, 5, _txt(value), align="R")
        ry += 6
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(max(y, ry) + 2)

    if getattr(invoice, "items", None):
        rows = [
            [i.description[:70], f"{i.quantity}", f"{i.unit_price}",
             f"{(i.quantity * i.unit_price).quantize(Decimal('0.01'))}"]
            for i in invoice.items
        ]
        pdf.items_table(["Item", "Qty", "Unit price", "Amount"], [96, 25, 32, 33], rows)
    elif time_entries:
        rows = [
            [f"{e.work_date}  {(e.description or 'Work')[:60]}", f"{e.hours}",
             f"{e.hourly_rate if e.hourly_rate is not None else (project.hourly_rate if project else '')}"]
            for e in time_entries
        ]
        pdf.items_table(["Time entry", "Hours", "Rate"], [126, 30, 30], rows)
    elif quote and quote.items:
        rows = [
            [i.description[:70], f"{i.quantity}", f"{i.unit_price}",
             f"{(i.quantity * i.unit_price).quantize(Decimal('0.01'))}"]
            for i in quote.items
        ]
        pdf.items_table(["Item", "Qty", "Unit price", "Amount"], [96, 25, 32, 33], rows)
    else:
        pdf.items_table(["Description", "Amount"], [140, 46], [["Professional services", f"{invoice.amount}"]])

    pdf.ln(2)
    pdf.total_line(f"Total ({invoice.currency})", f"{invoice.amount}")
    if invoice.fx_currency and invoice.fx_rate:
        converted = (invoice.amount * invoice.fx_rate).quantize(Decimal("0.01"))
        rate_str = f"{Decimal(invoice.fx_rate).normalize():f}"
        pdf.total_line(f"Equivalent ({invoice.fx_currency} @ {rate_str})", f"{converted:,}", bold=False)
    if paid_total and paid_total > 0:
        pdf.total_line("Paid", f"{paid_total}", bold=False)
        balance = (invoice.amount - paid_total).quantize(Decimal("0.01"))
        pdf.total_line("Balance due", f"{balance}")
        if balance <= 0:
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(22, 130, 60)
            pdf.cell(0, 10, "PAID - THANK YOU", align="R", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)

    # Payment details box (how to pay)
    if invoice.bank_name or invoice.account_number or invoice.account_title:
        pdf.ln(6)
        box_top = pdf.get_y()
        pdf.set_fill_color(*LIGHT)
        rows = [r for r in [
            ("Bank", invoice.bank_name),
            ("Account title", invoice.account_title),
            ("Account number", invoice.account_number),
        ] if r[1]]
        pdf.rect(12, box_top, 110, 8 + 6 * len(rows), "F")
        pdf.set_xy(16, box_top + 2)
        pdf.set_font("helvetica", "B", 8)
        pdf.set_text_color(*NAVY)
        pdf.cell(100, 5, "PAYMENT DETAILS")
        yy = box_top + 8
        for label, value in rows:
            pdf.set_xy(16, yy)
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(*GRAY)
            pdf.cell(32, 5, _txt(label))
            pdf.set_font("helvetica", "B", 9)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(70, 5, _txt(value))
            yy += 6
        pdf.set_y(yy + 2)
    return bytes(pdf.output())


class _LetterheadPDF(FPDF):
    """Minimal modern letterhead: white page, logo in a small navy tile,
    thin rules, generous whitespace — no heavy banner."""

    def __init__(self):
        super().__init__(format="A4")
        self.set_auto_page_break(auto=True, margin=32)
        self.set_margins(left=22, top=14, right=22)

    def header(self):
        # Brand tile: white logo needs a navy ground
        self.set_fill_color(*NAVY)
        try:
            self.rect(22, 14, 13, 13, "F", round_corners=True, corner_radius=3)
        except TypeError:  # older fpdf2 without rounded rects
            self.rect(22, 14, 13, 13, "F")
        if _LOGO_PATH.is_file():
            try:
                self.image(str(_LOGO_PATH), x=23.5, y=15.5, h=10)
            except Exception:
                pass
        self.set_xy(39, 15.5)
        self.set_font("helvetica", "B", 15)
        self.set_text_color(*NAVY)
        self.cell(80, 7, _txt(settings.app_name.replace(" API", "").upper()))
        self.set_xy(39, 22.2)
        self.set_font("helvetica", "", 7.5)
        self.set_text_color(*GRAY)
        self.cell(80, 4, _txt("  ".join((settings.frontend_url or "fuorix.com").replace("https://", "").replace("http://", "").replace("app.", ""))))

        # Right-aligned contact lines from COMPANY_DETAILS
        details = [p.strip() for p in (settings.company_details or "").replace("\n", "·").split("·") if p.strip()]
        ry = 15.0
        self.set_font("helvetica", "", 7.5)
        for line in details[:4]:
            self.set_xy(98, ry)
            self.cell(90, 3.6, _txt(line), align="R")
            ry += 4.2

        # Accent rule: short navy segment over a full hairline
        self.set_draw_color(226, 228, 233)
        self.set_line_width(0.3)
        self.line(22, 33, 188, 33)
        self.set_draw_color(*NAVY)
        self.set_line_width(1.1)
        self.line(22, 33, 50, 33)
        self.set_line_width(0.2)
        self.set_y(44)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_draw_color(226, 228, 233)
        self.set_line_width(0.3)
        self.line(22, 272, 188, 272)
        self.set_y(-21)
        self.set_font("helvetica", "", 7.5)
        self.set_text_color(*GRAY)
        footer = settings.company_details or f"Generated by {settings.app_name.replace(' API', '')}"
        self.cell(0, 5, _txt(footer.replace("\n", "  ·  ")), align="C")
        # Thin navy band along the bottom edge
        self.set_fill_color(*NAVY)
        self.rect(0, 293, 210, 4, "F")


def build_letter_pdf(letter) -> bytes:
    pdf = _LetterheadPDF()
    pdf.add_page()

    # Ref + date line
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(*GRAY)
    pdf.cell(90, 5, _txt(f"Ref: {letter.number}"))
    if letter.letter_date:
        pdf.cell(76, 5, _txt(f"{letter.letter_date:%d %B %Y}"), align="R")
    pdf.ln(10)

    # Recipient block
    if letter.recipient_name or letter.client:
        pdf.set_font("helvetica", "B", 10.5)
        pdf.set_text_color(20, 24, 34)
        pdf.cell(0, 5.5, _txt(letter.recipient_name or (letter.client.name if letter.client else "")), new_x="LMARGIN", new_y="NEXT")
        if letter.client and letter.recipient_name and letter.client.name != letter.recipient_name:
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(*GRAY)
            pdf.cell(0, 4.8, _txt(letter.client.name), new_x="LMARGIN", new_y="NEXT")
        if letter.recipient_address:
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(*GRAY)
            for line in letter.recipient_address.splitlines():
                if line.strip():
                    pdf.cell(0, 4.8, _txt(line.strip()), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(6)

    # Subject
    if letter.subject:
        pdf.set_font("helvetica", "B", 11.5)
        pdf.set_text_color(*NAVY)
        pdf.multi_cell(0, 6, _txt(letter.subject))
        pdf.ln(3)

    # Body: paragraphs with comfortable leading
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(55, 60, 70)
    for para in (letter.body or "").split("\n\n"):
        if para.strip():
            pdf.multi_cell(0, 5.6, _txt(para.strip()))
            pdf.ln(3)

    # Signature block: the author's saved signature image when there is one, else space for a wet signature
    if letter.signatory_name:
        pdf.ln(14)
        y = pdf.get_y()
        if y > 240:
            pdf.add_page()
            y = pdf.get_y()
        sig = _user_signature_path(letter, getattr(letter, "created_by", None))
        if sig:
            try:
                pdf.image(sig, x=22, y=y - 12, h=14)
            except Exception:
                pass
        pdf.set_draw_color(160, 166, 178)
        pdf.set_line_width(0.3)
        pdf.line(22, pdf.get_y(), 74, pdf.get_y())
        pdf.ln(2)
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(20, 24, 34)
        pdf.cell(0, 5.5, _txt(letter.signatory_name), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        if letter.signatory_title:
            pdf.cell(0, 4.8, _txt(letter.signatory_title), new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 4.8, _txt(settings.app_name.replace(" API", "")), new_x="LMARGIN", new_y="NEXT")
    return bytes(pdf.output())


def build_blank_letterhead() -> bytes:
    """An empty branded page for writing letters outside the app."""
    pdf = _LetterheadPDF()
    pdf.add_page()
    return bytes(pdf.output())


def _user_signature_path(obj, user_id):
    from sqlalchemy.orm import object_session
    from app.services import signature_service
    try:
        return signature_service.signature_path_for_user_id(object_session(obj), user_id)
    except Exception:
        return None


def _agreement_signatures(pdf, agreement) -> None:
    """Two signature boxes: the company (image when the sender/countersigner saved one) and the client
    (typed e-signature when accepted, otherwise a line for a wet signature)."""
    company = settings.app_name.replace(" API", "")
    client_name = agreement.client.name if agreement.client else "Client"
    y = pdf.get_y() + 4
    if y > 236:
        pdf.add_page()
        y = pdf.get_y() + 4
    sig_path = _user_signature_path(agreement, getattr(agreement, "countersigned_by", None)) if getattr(agreement, "countersigned_at", None) else None
    boxes = [
        (12, company, sig_path, getattr(agreement, "countersigned_by_name", None), getattr(agreement, "countersigned_at", None), None),
        (110, client_name, None, agreement.accepted_by_name if agreement.accepted_at else None, agreement.accepted_at, getattr(agreement, "signer_title", None)),
    ]
    for x, party, img, name, when, title in boxes:
        pdf.set_font("helvetica", "B", 8)
        pdf.set_text_color(*NAVY)
        pdf.set_xy(x, y)
        pdf.cell(88, 5, _txt(f"FOR {party.upper()}"))
        if img:
            try:
                pdf.image(img, x=x + 2, y=y + 6, h=14)
            except Exception:
                pass
        elif name and x == 110:
            # Typed e-signature in an italic face
            pdf.set_font("helvetica", "I", 15)
            pdf.set_text_color(20, 24, 34)
            pdf.set_xy(x + 2, y + 10)
            pdf.cell(86, 8, _txt(name))
        pdf.set_draw_color(160, 166, 178)
        pdf.set_line_width(0.3)
        pdf.line(x, y + 22, x + 88, y + 22)
        pdf.set_xy(x, y + 23)
        pdf.set_font("helvetica", "", 8)
        pdf.set_text_color(*GRAY)
        if name:
            label = name + (f", {title}" if title else "")
            if when:
                label += f" - {when:%d %b %Y}"
            pdf.cell(88, 4.5, _txt(label))
        else:
            pdf.cell(88, 4.5, _txt("Name, signature, date"))
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(y + 32)


def build_agreement_pdf(agreement) -> bytes:
    from app.services.agreement_template import label_for
    pdf = _BrandedPDF(label_for(getattr(agreement, "agreement_type", None)).upper())
    pdf.add_page()
    pdf.meta_row("Agreement", agreement.number)
    pdf.meta_row("Client", agreement.client.name if agreement.client else "-")
    pdf.meta_row("Title", agreement.title)
    if agreement.effective_date:
        pdf.meta_row("Effective date", str(agreement.effective_date))
    if agreement.contract_value:
        pdf.meta_row("Contract value", f"{agreement.contract_value} {agreement.currency}")
    if agreement.valid_until and agreement.status in ("draft", "sent", "expired"):
        pdf.meta_row("Sign by", str(agreement.valid_until))

    for idx, clause in enumerate(agreement.clauses or [], start=1):
        pdf.ln(4)
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(*NAVY)
        pdf.cell(0, 6, _txt(f"{idx}. {clause.get('heading', '')}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(60, 64, 72)
        pdf.multi_cell(0, 4.8, _txt(clause.get("body", "")))
    pdf.set_text_color(0, 0, 0)

    pdf.ln(4)
    _agreement_signatures(pdf, agreement)
    if agreement.status in ("signed", "terminated") and agreement.accepted_at:
        # Acceptance record box (the clickwrap/e-sign evidence)
        box_top = pdf.get_y()
        if box_top > 250:
            pdf.add_page()
            box_top = pdf.get_y()
        company = settings.app_name.replace(" API", "")
        via = {"link": "electronically via a secure signing link", "portal": "electronically via the client portal"}.get(agreement.acceptance_method, "by signature")
        signer = agreement.accepted_by_name or "-"
        if getattr(agreement, "signer_title", None):
            signer += f", {agreement.signer_title}"
        lines = [f"Signed for {agreement.client.name if agreement.client else 'the Client'} by {signer} on {agreement.accepted_at:%d %B %Y at %H:%M} UTC {via}."]
        evidence = []
        if getattr(agreement, "signer_email", None):
            evidence.append(f"email {agreement.signer_email}")
        if agreement.accepted_ip:
            evidence.append(f"IP {agreement.accepted_ip}")
        if evidence:
            lines.append("Identity record: " + ", ".join(evidence) + ".")
        if getattr(agreement, "countersigned_at", None):
            lines.append(f"Countersigned for {company} by {agreement.countersigned_by_name or '-'} on {agreement.countersigned_at:%d %B %Y at %H:%M} UTC.")
        elif agreement.status == "signed":
            lines.append(f"Countersignature for {company}: pending.")
        if getattr(agreement, "acceptance_hash", None):
            lines.append(f"Document fingerprint (SHA-256): {agreement.acceptance_hash}")
        if agreement.status == "terminated" and agreement.terminated_at:
            lines.append(f"Terminated on {agreement.terminated_at:%Y-%m-%d}: {agreement.termination_reason or ''}")
        box_h = 12 + 5 * len(lines)
        if box_top + box_h > 268:
            pdf.add_page()
            box_top = pdf.get_y()
        pdf.set_fill_color(*LIGHT)
        pdf.rect(12, box_top, 186, box_h, "F")
        pdf.set_xy(16, box_top + 3)
        pdf.set_font("helvetica", "B", 8)
        pdf.set_text_color(*NAVY)
        pdf.cell(170, 5, "ELECTRONIC SIGNATURE RECORD")
        pdf.set_xy(16, box_top + 9)
        pdf.set_font("helvetica", "", 8.5)
        pdf.set_text_color(0, 0, 0)
        for ln in lines:
            if ln.startswith("Terminated"):
                pdf.set_text_color(200, 40, 40)
            pdf.set_x(16)
            pdf.multi_cell(178, 4.6, _txt(ln))
        pdf.set_text_color(0, 0, 0)
        pdf.set_y(box_top + box_h + 4)
    return bytes(pdf.output())


def build_quote_pdf(quote) -> bytes:
    pdf = _BrandedPDF("PROPOSAL")
    pdf.add_page()
    pdf.meta_row("Proposal", quote.number)
    pdf.meta_row("Prepared for", quote.client.name if quote.client else (quote.lead.company_name if quote.lead else "-"))
    pdf.meta_row("Title", quote.title)
    if quote.valid_until:
        pdf.meta_row("Valid until", str(quote.valid_until))

    rows = [
        [i.description[:70], f"{i.quantity}", f"{i.unit_price}",
         f"{(i.quantity * i.unit_price).quantize(Decimal('0.01'))}"]
        for i in quote.items
    ]
    pdf.items_table(["Item", "Qty", "Unit price", "Amount"], [96, 25, 32, 33], rows)
    pdf.ln(2)
    pdf.total_line(f"Total ({quote.currency})", f"{quote.total}")
    if quote.terms:
        pdf.ln(6)
        pdf.set_font("helvetica", "B", 9)
        pdf.cell(0, 6, "Terms", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.multi_cell(0, 5, _txt(quote.terms))
    return bytes(pdf.output())
