"""Branded PDF documents for invoices and quotes (fpdf2, pure python)."""
from decimal import Decimal
from fpdf import FPDF
from app.config import get_settings

settings = get_settings()

NAVY = (1, 24, 78)
GRAY = (110, 118, 130)
LIGHT = (243, 244, 247)


def _txt(value) -> str:
    """Core fonts are latin-1 only; degrade unknown glyphs instead of crashing."""
    return str(value if value is not None else "").encode("latin-1", "replace").decode("latin-1")


class _BrandedPDF(FPDF):
    def __init__(self, doc_title: str):
        super().__init__()
        self.doc_title = doc_title
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 26, "F")
        self.set_font("helvetica", "B", 16)
        self.set_text_color(255, 255, 255)
        self.set_xy(12, 8)
        self.cell(100, 10, _txt(settings.app_name.replace(" API", "")))
        self.set_font("helvetica", "B", 13)
        self.set_xy(120, 8)
        self.cell(78, 10, _txt(self.doc_title), align="R")
        self.set_y(34)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-16)
        self.set_font("helvetica", "", 8)
        self.set_text_color(*GRAY)
        footer = settings.company_details or f"Generated by {settings.app_name.replace(' API', '')}"
        self.cell(0, 8, _txt(footer.replace("\n", "  ·  ")), align="C")

    def meta_row(self, label: str, value: str):
        self.set_font("helvetica", "", 10)
        self.set_text_color(*GRAY)
        self.cell(40, 6, _txt(label))
        self.set_text_color(0, 0, 0)
        self.set_font("helvetica", "B", 10)
        self.cell(0, 6, _txt(value), new_x="LMARGIN", new_y="NEXT")

    def items_table(self, headers: list[str], widths: list[int], rows: list[list[str]]):
        self.ln(4)
        self.set_font("helvetica", "B", 9)
        self.set_fill_color(*NAVY)
        self.set_text_color(255, 255, 255)
        for h, w in zip(headers, widths):
            self.cell(w, 8, _txt(h), fill=True, align="R" if h != headers[0] else "L")
        self.ln()
        self.set_text_color(0, 0, 0)
        self.set_font("helvetica", "", 9)
        fill = False
        for row in rows:
            if fill:
                self.set_fill_color(*LIGHT)
            for i, (cell, w) in enumerate(zip(row, widths)):
                self.cell(w, 7, _txt(cell), fill=fill, align="R" if i != 0 else "L")
            self.ln()
            fill = not fill

    def total_line(self, label: str, value: str, bold: bool = True):
        self.set_font("helvetica", "B" if bold else "", 11 if bold else 10)
        self.cell(140, 8, _txt(label), align="R")
        self.cell(46, 8, _txt(value), align="R", new_x="LMARGIN", new_y="NEXT")


def build_invoice_pdf(invoice, client, project, time_entries, quote, paid_total: Decimal) -> bytes:
    pdf = _BrandedPDF("INVOICE")
    pdf.add_page()
    pdf.meta_row("Invoice", invoice.number)
    pdf.meta_row("Billed to", client.name if client else "-")
    if project:
        pdf.meta_row("Project", project.name)
    if invoice.issued_at:
        pdf.meta_row("Issued", str(invoice.issued_at))
    if invoice.due_date:
        pdf.meta_row("Due", str(invoice.due_date))
    pdf.meta_row("Status", invoice.status)

    if time_entries:
        rows = [
            [f"{e.work_date}  {(e.description or 'Work')[:60]}", f"{e.hours}",
             f"{e.hourly_rate if e.hourly_rate is not None else (project.hourly_rate if project else '')}"]
            for e in time_entries
        ]
        pdf.items_table(["Time entry", "Hours", "Rate"], [126, 30, 30], rows)
    elif quote and quote.items:
        rows = [
            [i.description[:70], f"{i.quantity}", f"{i.unit_price}",
             f"{(i.quantity * i.unit_price).quantize(Decimal('0.01'))}"]
            for i in quote.items
        ]
        pdf.items_table(["Item", "Qty", "Unit price", "Amount"], [96, 25, 32, 33], rows)
    else:
        pdf.items_table(["Description", "Amount"], [140, 46], [["Professional services", f"{invoice.amount}"]])

    pdf.ln(2)
    pdf.total_line(f"Total ({invoice.currency})", f"{invoice.amount}")
    if paid_total and paid_total > 0:
        pdf.total_line("Paid", f"{paid_total}", bold=False)
        pdf.total_line("Balance due", f"{(invoice.amount - paid_total).quantize(Decimal('0.01'))}")
    return bytes(pdf.output())


def build_quote_pdf(quote) -> bytes:
    pdf = _BrandedPDF("PROPOSAL")
    pdf.add_page()
    pdf.meta_row("Proposal", quote.number)
    pdf.meta_row("Prepared for", quote.client.name if quote.client else (quote.lead.company_name if quote.lead else "-"))
    pdf.meta_row("Title", quote.title)
    if quote.valid_until:
        pdf.meta_row("Valid until", str(quote.valid_until))

    rows = [
        [i.description[:70], f"{i.quantity}", f"{i.unit_price}",
         f"{(i.quantity * i.unit_price).quantize(Decimal('0.01'))}"]
        for i in quote.items
    ]
    pdf.items_table(["Item", "Qty", "Unit price", "Amount"], [96, 25, 32, 33], rows)
    pdf.ln(2)
    pdf.total_line(f"Total ({quote.currency})", f"{quote.total}")
    if quote.terms:
        pdf.ln(6)
        pdf.set_font("helvetica", "B", 9)
        pdf.cell(0, 6, "Terms", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.multi_cell(0, 5, _txt(quote.terms))
    return bytes(pdf.output())
